services:
  client-api:
    privileged: true
    tty: true
    image: 'test-env:latest'
    volumes:
      - /home/pi/workspace:/app
    ports:
      - 8080:8080
    container_name: client-api
    depends_on:
      - db
    links:
      - db

  sensor-managment:
    privileged: true
    tty: true
    image: 'test-env:latest'
    volumes:
      - /home/pi/workspace:/app
    container_name: sensor-managment
    depends_on:
      - db
    links:
      - db

  db:
    image: 'arm32v7/postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres