services:
  client-api:
    image: 'test-env:latest'
    container_name: client-api
    privileged: true
    tty: true
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    depends_on:
      - postgres
    links:
      - postgres

  sensor-managment:
    image: 'test-env:latest'
    container_name: sensor-managment
    privileged: true
    tty: true
    volumes:
      - ./:/app
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: 'arm32v7/postgres:latest'
    container_name: postgres
    environment:
      - POSTGRES_ROOT_PASSWORD=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  front-end:
    image: 'node-env:latest'
    container_name: front-end
    volumes:
      - ./:/app
    ports:
      - "80:80"
    command: './reload_frontend.sh'