spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres?currentSchema="sensors"
    username: root
    password: postgres
    initialization-mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
